### ISSUE TITLE
Combining Tensor and Dict inputs

### ISSUE THREAD

**Issue by JesusPinedaC** [DeepTrackAI/deeplay#32]
In our latest pull request [#31](https://github.com/DeepTrackAI/deeplay/pull/31), we've added the ability to take dictionaries as inputs for the network. Now, we're figuring out how to smoothly blend layers that usually work with tensors and those set up for dictionaries.

So, here's the question: should we make it a rule that if just one layer in a Sequential model expects dictionaries, all layers roll with it and accept dictionary inputs automatically? Your thoughts on this would be super helpful!

**Comment by giovannivolpe** [comment]
I'd be ok with this (if just one layer in a Sequential model expects dictionaries, all layers roll with it and accept dictionary inputs automatically), but I don't have hands on experience so I don't know if this can cause side effects.

**Comment by BenjaminMidtvedt** [comment]
I've thought about this for a bit. I'm also a bit delirious from fever so make sure it makes sense. I think that we should always have a dict in the background. We should verify that this does not cause a significant speed loss. 

In DeeplayModule we overload the __call__ method to pull the correct values and put them into the right entries. Thus all subclasses handle it automatically.

In Layer, we monkey patch as we currently do. Perhaps we monkey patch the __call__ instead for consistency. 

Per default, we take matching keys to the call signature of forward. So we only need to call set_input_map if there's a naming mismatch. This should be precomputed to avoid runtime computations. 

If there is only one output, it is passed to "x" unless otherwise specified. If there are multiple, we can check some class variable for the correct mapping. This variable is configured by set_output_map. 

We can try to check if there is no need for a dict based on the connectivity, buy I think this will be hard and prone to bugs.
