### ISSUE TITLE
Logs not populating after inference when model is initialized before an application

### ISSUE THREAD

**Issue by JesusPinedaC** [DeepTrackAI/deeplay#92]
I've encountered a problem where, if I create a model prior to starting a deeplay application, `application.logs` remains empty following inference. Logs are instead stored in `model.logs`. For example:

``` Python
import torch
import torch.nn as nn

import deeplay as dl

model = dl.LayerActivation(
    layer=dl.Layer(nn.Linear, 1, 10),
    activation=dl.Layer(nn.Sigmoid),
)
model.layer.log_output("x_transformed")
model = model.create()

classifier = dl.BinaryClassifier(
    model=model,
    optimizer=dl.Adam(lr=0.01),
).create()

x = torch.randn(2, 1)
y = classifier(x)

print(classifier.logs) # same for classifier.model.logs
# {}

print(model.logs["x_transformed"].shape)
# (2, 10)
```

if `model = model.create()` is skipped, then `classifier.logs` is populated while `model.logs` does not exist. Is this an expected behavior?

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC 
> if model = model.create() is skipped, then classifier.logs is populated while model.logs does not exist. Is this an expected behavior?

Yes, this is expected. logs will always exist on the root module. So here, classifier is correctly set as the root module, since it wraps model. I might add dereferencing using properties such that`model.logs` becomes `model.root_module.logs`.

Your example is not expected behavior, but I'm not sure I hate it. `create` and `build` kind of "compiles" the model, and it would make some sense if that locks in the location of `logs`

**Comment by BenjaminMidtvedt** [comment]
To clarify, currently, if you do both
```
model.create() or model.build()
classifier.create() or classifier.build()
```
-> is in model.logs

if you do only
```
classifier.build() or classifier.create()
```
-> is in classifier.logs

**Comment by JesusPinedaC** [comment]
Great, thanks!
